/* Small authored layer for material that is not already structured elsewhere.
   Factual answers still point back to a public page. */
var LAB_ASSISTANT_KNOWLEDGE = {
  pages: [
    { title:'LaB Media Home', url:'index.html', tags:'home start lab media films notebook tools',
      summary:'The front door to LaB’s reel, tools and public filmmaking notebook.' },
    { title:'The Reel', url:'portfolio.html', tags:'films work portfolio production notes behind the scenes bts',
      summary:'Eight films with production timelines, honest notes and behind-the-scenes galleries.' },
    { title:'Michigan Film Events', url:'events.html', tags:'events screenings festivals community detroit michigan',
      summary:'Upcoming Michigan screenings, gatherings and evergreen film organizations.' },
    { title:'Watch & Learn', url:'learn.html', tags:'learn tutorials youtube channels filmmaking education references',
      summary:'Filmmaking channels and reference sites worth learning from.' },
    { title:'Software & Assets', url:'resources.html', tags:'software ai music stock footage fonts type 3d code tools',
      summary:'Checked tools and assets for making films and building things.' },
    { title:'Gear & Flight', url:'sourcing.html', tags:'rent rental buy cameras lenses drone fpv training equipment',
      summary:'Places to buy, rent, research and learn production gear and flight.' },
    { title:'People & Community', url:'people.html', tags:'people collaborators festivals groups community michigan',
      summary:'Collaborators, festivals and Michigan film communities.' },
    { title:'LaB’s Kit', url:'gear.html', tags:'gear kit owned borrowed shared cameras lenses lights audio drones software',
      summary:'The gear LaB owns, plus collaborator equipment clearly marked as shared.' },
    { title:'Your Kit', url:'mykit.html', tags:'saved favorites bookmarks kit privacy browser storage',
      summary:'Resources you save from the notebook, kept only in this browser.' },
    { title:'Story Generator', url:'ideas.html', tags:'story idea prompt generator genre character setting constraint',
      summary:'Roll a genre, character, setting and constraint when you want to make something.' },
    { title:'SkyBound', url:'skybound.html', tags:'drone fpv learn simulator part 107 flight path',
      summary:'A practical drone path: simulate, learn, build a kit, then work toward Part 107.' },
    { title:'LaB Assistant', url:'assistant.html', tags:'assistant ask search films gear resources events local model free',
      summary:'Ask the site about LaB’s films, kit, checked resources, events and build notes.' },
    { title:'About LaB', url:'contact.html', tags:'about bobby contact email shelby township detroit work hire',
      summary:'LaB Media is Bobby: one person with a camera, a full-time job and a weekend filmmaking habit.' },
    { title:'How the Site Is Built', url:'colophon.html', tags:'site code html css javascript privacy cookies github pages build',
      summary:'A hand-built static site: plain HTML, CSS and JavaScript, with no framework or backend.' }
  ],
  films: [
    { title:'Anthony Brass', url:'portfolio.html#artist', year:'2024', kind:'Artist spotlight',
      tags:'artist documentary portrait paint studio natural light one day',
      summary:'An intimate artist portrait filmed in Anthony Brass’s home studio in one day.' },
    { title:'MOZ Interiors', url:'portfolio.html#moz', year:'2024', kind:'Commercial · Brand film',
      tags:'commercial brand interior design detroit architecture one day',
      summary:'A one-day brand film for a Detroit interior design studio, built around the spaces themselves.' },
    { title:'The Pandys', url:'portfolio.html#pandys', year:'2024', kind:'Music video · Live session',
      tags:'music video band rehearsal live performance detroit',
      summary:'A live-session music video built around raw rehearsal energy and minimal interference.' },
    { title:'Trail Dead', url:'portfolio.html#horror', year:'2025', kind:'Short film · Horror',
      tags:'horror timed competition horror film roulette award editing 51 days',
      summary:'A timed-competition horror short built largely in the cut; it won Best Editing at Horror Film Roulette 2025.' },
    { title:'Lookout', url:'portfolio.html#comedy', year:'2025', kind:'Short film · Comedy',
      tags:'comedy short funny timing',
      summary:'A comedy short built around sharp writing and timing.' },
    { title:'It’s a Boy', url:'portfolio.html#itsaboy', year:'2026', kind:'Short film · Comedy',
      tags:'comedy short comedy roll michigan unreleased',
      summary:'A late entry to The Comedy Roll, shot across three days in a Michigan spring; it is not public yet.' },
    { title:'Scattered', url:'portfolio.html#scattered', year:'2026', kind:'Short film · 48 Hour',
      tags:'48 hour detroit film project timed six minutes festival',
      summary:'Made for the Detroit 48 Hour Film Project and uploaded with six minutes left.' },
    { title:'Le Juicé', url:'portfolio.html#lejuice', year:'2026', kind:'Commercial · Brand film',
      tags:'commercial brand juice rochester moz interiors green terrazzo',
      summary:'A Rochester juice-bar brand film made for Le Juicé and MOZ Interiors.' }
  ],
  faqs: [
    { title:'What is LaB Media?', url:'contact.html',
      tags:'what who lab media bobby about',
      answer:'LaB Media is Bobby: one person with a camera, a full-time job and a habit of finishing films on weekends. The site is both a reel and a public folder of useful filmmaking links.' },
    { title:'Is LaB taking projects?', url:'contact.html',
      tags:'hire hiring available project shoot booking client work',
      answer:'Probably not. LaB is a hobby site, not a booking funnel, and Bobby is not currently taking projects. He is open to talking shop or answering how something was made.' },
    { title:'How is the site built?', url:'colophon.html',
      tags:'built code framework backend hosting github pages javascript html css cookies',
      answer:'It is hand-written HTML, CSS and JavaScript with no framework, build step or backend. It runs on free hosting; the domain is the recurring cost.' },
    { title:'Does the site track me?', url:'colophon.html',
      tags:'privacy cookies tracking analytics data',
      answer:'The site uses no cookies or persistent visitor identifiers. Videos are click-to-load, and GoatCounter provides privacy-minded aggregate visit counts.' },
    { title:'Where are saved resources kept?', url:'mykit.html',
      tags:'saved kit favorites bookmarks localstorage browser sync privacy',
      answer:'Your Kit is stored in this browser with localStorage. It does not create an account or sync anywhere.' },
    { title:'Where should I start?', url:'index.html',
      tags:'start beginner where navigation help',
      answer:'For films, start with The Reel. To learn, open Watch & Learn. For filmmaking tools, use Software & Assets. If drones are the goal, start with SkyBound.' },
    { title:'How does this assistant work?', url:'assistant.html',
      tags:'assistant ai model ollama local search how work privacy',
      answer:'The published assistant is model-free: your question stays in the browser and is matched against the site’s structured data. In the localhost dogfood version, a narrow gateway can give that retrieved answer to one fixed Ollama model for phrasing. For a :cloud model, the raw question stays on the Mac and only the already-sourced public answer is sent for cloud phrasing. The browser never talks to Ollama directly, and sourced retrieval remains the fallback.' }
  ]
};

if (typeof window !== 'undefined') window.LAB_ASSISTANT_KNOWLEDGE = LAB_ASSISTANT_KNOWLEDGE;
