/* Small authored layer for material that is not already structured elsewhere.
   Factual answers still point back to a public page. */
var LAB_ASSISTANT_KNOWLEDGE = {
  pages: [
    { title:'LaB Media Home', url:'index.html', tags:'home start lab media films notebook tools',
      summary:'The front door to LaB’s reel, tools and public filmmaking notebook.' },
    { title:'The Reel', url:'portfolio.html', tags:'films work portfolio production notes behind the scenes bts',
      summary:'Eight films with production timelines, honest notes and behind-the-scenes galleries.' },
    { title:'Michigan Film Events', url:'events.html', tags:'events screenings festivals community detroit michigan',
      summary:'Upcoming Michigan screenings, gatherings and evergreen film organizations.' },
    { title:'Watch & Learn', url:'learn.html', tags:'learn tutorials youtube channels filmmaking education references',
      summary:'Filmmaking channels and reference sites worth learning from.' },
    { title:'Software & Assets', url:'resources.html', tags:'software ai music stock footage fonts type 3d code tools',
      summary:'Checked tools and assets for making films and building things.' },
    { title:'Gear & Flight', url:'sourcing.html', tags:'rent rental buy cameras lenses drone fpv training equipment',
      summary:'Places to buy, rent, research and learn production gear and flight.' },
    { title:'People & Community', url:'people.html', tags:'people collaborators festivals groups community michigan',
      summary:'Collaborators, festivals and Michigan film communities.' },
    { title:'LaB’s Kit', url:'gear.html', tags:'gear kit owned borrowed shared cameras lenses lights audio drones software',
      summary:'The gear LaB owns, plus collaborator equipment clearly marked as shared.' },
    { title:'Your Kit', url:'mykit.html', tags:'saved favorites bookmarks kit privacy browser storage',
      summary:'Resources you save from the notebook, kept only in this browser.' },
    { title:'Story Generator', url:'ideas.html', tags:'story idea prompt generator genre character setting constraint',
      summary:'Roll a genre, character, setting and constraint when you want to make something.' },
    { title:'Golden Hour Planner', url:'sun.html', tags:'golden hour blue hour sun sunrise sunset solar noon elevation direction date location wind cloud cover overcast filtered diffused moon lunar phase waxing waning crescent gibbous full phrases light windows call sheet',
      summary:'A date- and location-aware filmmaking planner with calculated light windows, live cloud-aware guidance for today, separate sun and phase-aware moon paths, and a copyable day plan.' },
    { title:'SkyBound : Weather', url:'droneweather.html', tags:'drone weather skybound live wind gusts visibility precipitation cloud cover overcast flight safety thresholds open meteo checklist night flying animated scene local time sunset twilight blue hour moon lunar phase waxing waning',
      summary:'Live Metro Detroit wind, cloud and weather guidance, conservative flight thresholds, a local-time scene with a phase-aware moon, and a persistent 18-point pre-flight checklist.' },
    { title:'Aspect Ratio Previewer', url:'aspect.html', tags:'aspect ratio crop framing letterbox anamorphic scope vertical image video local privacy 1080p 4k multiple files',
      summary:'Preview common cinema and social crops against sample frames or local images and video, with exact 1080p and 4K active-pixel dimensions and no uploads.' },
    { title:'SkyBound : Drone', url:'skybound.html', tags:'skybound drone fpv learn simulator part 107 flight path training licence license',
      summary:'A practical drone path: simulate, learn, build a kit, then work toward Part 107.' },
    { title:'LaB Assistant', url:'assistant.html', tags:'assistant ask search films gear resources events sourced model ollama nemotron hybrid privacy',
      summary:'Ask the site about LaB’s films, kit, checked resources, events and build notes.' },
    { title:'About LaB', url:'contact.html', tags:'about bobby contact email shelby township detroit work hire',
      summary:'LaB Media is Bobby: one person with a camera, a full-time job and a weekend filmmaking habit.' },
    { title:'How the Site Is Built', url:'colophon.html', tags:'site code html css javascript privacy cookies github pages build',
      summary:'A hand-built static site: plain HTML, CSS and JavaScript with no framework, plus one small Worker for optional AI phrasing.' }
  ],
  films: [
    { title:'Anthony Brass', url:'portfolio.html#artist', year:'2024', filmed:'March 4, 2024', kind:'Artist spotlight',
      tags:'artist documentary portrait paint studio natural light one day video watch youtube player',
      summary:'An intimate artist portrait filmed in Anthony Brass’s home studio in one day.',
      videoUrl:'https://www.youtube.com/watch?v=CPvxM8GrCg8' },
    { title:'MOZ Interiors', url:'portfolio.html#moz', year:'2024', filmed:'July 1, 2024', kind:'Commercial · Brand film',
      tags:'commercial brand interior design detroit architecture one day video watch youtube player',
      summary:'A one-day brand film for a Detroit interior design studio, built around the spaces themselves.',
      videoUrl:'https://www.youtube.com/watch?v=HtF4L9RpkaU' },
    { title:'The Pandys', url:'portfolio.html#pandys', year:'2024', filmed:'January 2024', kind:'Music video · Live session',
      tags:'music video band rehearsal live performance detroit video watch youtube player',
      summary:'A live-session music video built around raw rehearsal energy and minimal interference.',
      videoUrl:'https://www.youtube.com/watch?v=ZXYtZmIRiRI' },
    { title:'Trail Dead', url:'portfolio.html#horror', year:'2025', filmed:'September 20–29, 2025', kind:'Short film · Horror',
      tags:'horror timed competition horror film roulette award editing 51 days video watch youtube player',
      summary:'A timed-competition horror short built largely in the cut; it won Best Editing at Horror Film Roulette 2025.',
      videoUrl:'https://www.youtube.com/watch?v=rtEs8chuDlM' },
    { title:'Lookout', url:'portfolio.html#comedy', year:'2025', filmed:'May 1, 5 and 20, 2025', kind:'Short film · Comedy',
      tags:'comedy short funny timing video watch youtube player',
      summary:'A comedy short built around sharp writing and timing.',
      videoUrl:'https://www.youtube.com/watch?v=G0zfFWwQuZA' },
    { title:'It’s a Boy', url:'portfolio.html#itsaboy', year:'2026', filmed:'April 25, 27, 28 and 29, 2026', kind:'Short film · Comedy',
      tags:'comedy short comedy roll michigan',
      summary:'A late entry to The Comedy Roll, shot across four days in a Michigan spring; the competition cut is public on YouTube and a finished version is in the works.' },
    { title:'Scattered', url:'portfolio.html#scattered', year:'2026', filmed:'July 25–26, 2026', kind:'Short film · 48 Hour',
      tags:'48 hour detroit film project timed six minutes festival',
      summary:'Made for the Detroit 48 Hour Film Project and uploaded with six minutes left.' },
    { title:'Le Juicé', url:'portfolio.html#lejuice', year:'2026', filmed:'June 1, 2026', kind:'Commercial · Brand film',
      tags:'commercial brand juice rochester moz interiors green terrazzo',
      summary:'A Rochester juice-bar brand film made for Le Juicé and MOZ Interiors.' }
  ],
  faqs: [
    { title:'What is LaB Media?', url:'contact.html',
      tags:'what who lab media bobby about',
      answer:'LaB Media is Bobby: one person with a camera, a full-time job and a habit of finishing films on weekends. The site is both a reel and a public folder of useful filmmaking links.' },
    { title:'Is LaB taking projects?', url:'contact.html',
      tags:'hire hiring available project shoot booking client work',
      answer:'Probably not. LaB is a hobby site, not a booking funnel, and Bobby is not currently taking projects. He is open to talking shop or answering how something was made.' },
    { title:'How is the site built?', url:'colophon.html',
      tags:'built code framework backend hosting github pages javascript html css cookies',
      answer:'It is hand-written HTML, CSS and JavaScript with no framework or build step. The pages run on free hosting; one small Cloudflare Worker protects optional AI phrasing, and the domain is the recurring cost.' },
    { title:'Does the site track me?', url:'colophon.html',
      tags:'privacy cookies tracking analytics data',
      answer:'The site uses no cookies or persistent visitor identifiers. Videos are click-to-load, and GoatCounter provides privacy-minded aggregate visit counts.' },
    { title:'Where are saved resources kept?', url:'mykit.html',
      tags:'saved kit favorites bookmarks localstorage browser sync privacy',
      answer:'Your Kit is stored in this browser with localStorage. It does not create an account or sync anywhere.' },
    { title:'Where should I start?', url:'index.html',
      tags:'start beginner where navigation help',
      answer:'For films, start with The Reel. To learn, open Watch & Learn. For filmmaking tools, use Software & Assets. If drones are the goal, start with SkyBound.' },
    { title:'Who took the On Set photographs?', url:'contact.html',
      tags:'photo photos photograph photographs photographer photography credit credited stills who shot took taken al krakosky alkrak3 on set onset behind the scenes bts gallery the hook scattered about page iphone',
      answer:'The About page holds two On Set folds. The Hook: fourteen photographs by Al Krakosky, across both shoot days, March 21 on a 35mm and March 28 on an 85mm, the same Sony ILCE-7RM2 body each time; his work is at instagram.com/alkrak3. Scattered: three photographs from the 48-hour weekend, taken by Bobby on an iPhone 17 Pro, except the raccoon rescue on July 26, which is Al’s.' },
    { title:'What is Sideways?', url:'contact.html',
      tags:'sideways sideways studio sideways animation sideways lab animator animation studio al krakosky albert krakosky joe krakosky brothers brother collaborator who is al full name',
      answer:'Sideways Studio is an animation studio run by Al Krakosky (Albert Krakosky III) and his brother Joe Krakosky. Al is LaB’s closest collaborator across the reel, and the photographer behind the On Set photographs on the About page; Scattered was entered in the Detroit 48 Hour Film Project under the team name Sideways Lab. The studio is at sidewaysstudio.net, and on Instagram at instagram.com/sideways_animation.' },
    { title:'Does Scattered have a poster?', url:'portfolio.html#scattered',
      tags:'poster posters key art artwork scattered 48 hour cast credits joe krakosky robert baldwin kyle keaser albert krakosky sideways lab who is in it starring',
      answer:'Yes. The Scattered poster is on the reel beside the film’s spec sheet. It was made by Sideways Studio, and it names the cast: Joe Krakosky, Robert Baldwin, Kyle Keaser and Albert Krakosky III. It had never been posted anywhere before it went up here. The film itself is still awaiting its Detroit 48 Hour Film Project screening.' },
    { title:'How does this assistant work?', url:'assistant.html',
      tags:'assistant ai model ollama local search how work privacy',
      answer:'The published assistant matches your question against the site’s structured data in the browser. In the default hybrid mode, a protected Cloudflare Worker may hand only that already-public answer to the fixed Nemotron 3 Super model for more natural phrasing. The raw visitor question is not sent to Ollama, the API key never reaches the browser, and sourced retrieval remains the fallback. Switch to Sourced only to make no model request at all.' }
  ]
};

if (typeof window !== 'undefined') window.LAB_ASSISTANT_KNOWLEDGE = LAB_ASSISTANT_KNOWLEDGE;
