const eventsData = [
    {
        id: 'dfa-tv-premiere-night-2026',
        title: 'Detroit Filmmaker Awards x Detroit Public Access TV Premiere Night',
        type: 'screening',
        startDate: '2026-02-06',
        startTime: '19:00',
        endTime: '21:00',
        location: 'Detroit, MI',
        venue: 'Detroit Public Access TV Studios',
        organizer: 'Detroit Filmmaker Awards',
        description: 'Community screening highlighting DFA award winners on the big screen with a post-show Q&A and networking mixer.',
        url: 'https://detroitfilmmakerawards.com/',
        website: 'https://detroitfilmmakerawards.com/',
        verification: 'verified',
        thumbnail: 'images/DFAXDFM.JPG'
    },
    {
        id: 'lab-community-meetup-2026-01',
        title: 'LaB Community Meetup: Winter Collab Night',
        type: 'meetup',
        startDate: '2026-01-23',
        startTime: '18:30',
        endTime: '20:30',
        location: 'Shelby Township, MI',
        venue: 'LaB Media Studio',
        organizer: 'LaB Media',
        description: 'Bring a current project, meet local collaborators, and share updates. Short intros followed by open networking.',
        url: 'https://labmedia.work/events.html',
        website: 'https://labmedia.work/events.html',
        verification: 'verified'
    },
    {
        id: 'farmington-film-fest-2026',
        title: 'Farmington Film Festival',
        type: 'festival',
        startDate: '2026-03-12',
        endDate: '2026-03-15',
        location: 'Farmington, MI',
        venue: 'Farmington Civic Theater',
        organizer: 'Kickstart Farmington',
        description: 'Local indie film festival featuring shorts, features, and community Q&As with Detroit-area filmmakers.',
        url: 'https://kickstartfarmington.org/film/',
        website: 'https://kickstartfarmington.org/film/',
        verification: 'verified'
    },
    {
        id: 'royal-oak-doc-workshop-2026',
        title: 'Documentary Workshop: Shooting in the Field',
        type: 'workshop',
        startDate: '2026-02-21',
        startTime: '10:00',
        endTime: '15:00',
        location: 'Royal Oak, MI',
        venue: 'Royal Oak Creative Lab',
        organizer: 'Royal Oak Creative Lab',
        description: 'Hands-on workshop covering vérité technique, interview coverage, and low-budget sound kits for documentary crews.',
        url: 'https://www.instagram.com/labmedia.work/',
        website: 'https://www.instagram.com/labmedia.work/',
        verification: 'tbd',
        verificationLabel: 'Check IG'
    },
    {
        id: 'detroit-short-docs-2025',
        title: 'Detroit Short Docs Showcase',
        type: 'screening',
        startDate: '2025-10-18',
        startTime: '19:30',
        endTime: '21:30',
        location: 'Detroit, MI',
        venue: 'Cinema Detroit',
        organizer: 'Cinema Detroit',
        description: 'A curated night of Detroit-made short documentaries with filmmaker Q&A and audience discussion.',
        url: 'https://cinemadetroit.org/',
        website: 'https://cinemadetroit.org/',
        verification: 'verified',
        photos: ['images/DFAXDFM.JPG']
    },
    {
        id: 'auburn-hills-screenwriters-mixer-2024',
        title: 'Auburn Hills Screenwriters Mixer',
        type: 'meetup',
        startDate: '2024-11-07',
        startTime: '18:00',
        endTime: '20:00',
        location: 'Auburn Hills, MI',
        venue: 'Auburn Hills Community Center',
        organizer: 'Auburn Hills Arts Council',
        description: 'Casual mixer for screenwriters and filmmakers to share loglines and connect on new projects.',
        url: 'https://www.auburnhills.org/',
        website: 'https://www.auburnhills.org/',
        verification: 'verified',
        photos: ['images/Lookout.jpg', 'images/TrailDead.jpg']
    },
    {
        id: 'detroit-filmmaker-awards-deadline-2026',
        title: 'Detroit Filmmaker Awards: Submission Deadline',
        type: 'deadline',
        startDate: '2026-01-31',
        location: 'Detroit, MI',
        organizer: 'Detroit Filmmaker Awards',
        description: 'Final deadline to submit projects for the Detroit Filmmaker Awards season. Double-check eligibility and deliverables.',
        url: 'https://detroitfilmmakerawards.com/',
        website: 'https://detroitfilmmakerawards.com/',
        verification: 'verified',
        deadlineDate: '2026-01-31'
    }
];

const eventsPosterData = [
    {
        id: 'frames-fabrics-2026',
        title: "Frames & Fabrics: The Art of Film in Detroit",
        type: 'screening',
        startDate: '2026-01-31',
        startTime: '15:00',
        endTime: '20:00',
        location: 'Detroit, MI',
        venue: 'Heilmann Rec Center',
        organizer: 'Film Detroit',
        description: 'A Film Detroit community showcase celebrating local filmmakers with screenings, fabric-inspired set pieces, and creative workshops.',
        url: 'https://detroitmi.gov/',
        website: 'https://detroitmi.gov/',
        verification: 'tbd',
        verificationLabel: 'Check site',
        posterImage: 'images/events/frames-fabrics-2026.svg'
    }
];
